export const TEMPLATES = {
  TEMPLATE_A: 'TEMPLATE_A',
  TEMPLATE_B: 'TEMPLATE_B',
  TEMPLATE_D: 'TEMPLATE_D',
  BILL_OF_SUPPLY: 'BILL_OF_SUPPLY',
  SIMPLIFIED_3_COL: 'SIMPLIFIED_3_COL',
  TAX_INVOICE: 'TAX_INVOICE',
  FUEL_TOLL_SLIP: 'FUEL_TOLL_SLIP',
  CONSOLIDATED: 'CONSOLIDATED',
  DAILY_LR: 'DAILY_LR',
};
