export const UI_TABS = {
  // Main Tabs
  ANALYTICS: 'ANALYTICS',
  COMPLIANCE: 'COMPLIANCE',
  DAILY_RUN_SHEET: 'DAILY_RUN_SHEET',
  DRIVER_MANAGEMENT: 'DRIVER_MANAGEMENT',
  FINANCE: 'FINANCE',
  FLEET_MANAGEMENT: 'FLEET_MANAGEMENT',
  LEDGER: 'LEDGER',
  MANAGEMENT: 'MANAGEMENT',
  MAP: 'MAP',
  PAYROLL: 'PAYROLL',
  PROFILE: 'PROFILE',
  SUBSCRIPTION: 'SUBSCRIPTION',
  SUPPLIERS: 'SUPPLIERS',
  TRANSACTIONS: 'TRANSACTIONS',
  
  // Lowercase Tabs
  OVERVIEW: 'overview',
  ONBOARD: 'onboard',
  TENANTS: 'tenants',

  // Accountant Tabs
  BANK_MATCHING: 'BANK_MATCHING',
  BILLING: 'BILLING',
  BOOKKEEPING: 'BOOKKEEPING',
  FLIPKART_MIS: 'FLIPKART_MIS',
  OUTSTANDING: 'OUTSTANDING',
};

export const TIME_RANGES = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  YEARLY: 'yearly',
  DAY: 'day',
  WEEK: 'week',
  MONTH: 'month',
  YEAR: 'year',
  SIX_MONTH: '6month',
  ALL: 'all',
};

export const VIEW_MODES = {
  CONSOLIDATED: 'CONSOLIDATED',
  DAILY: 'DAILY',
  MONTHLY_GEN: 'MONTHLY_GEN',
  PORTAL_TRACKER: 'PORTAL_TRACKER',
};
