import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto p-8 bg-white shadow-md mt-10 rounded-lg text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="mb-4 text-sm text-gray-500">Last updated: July 16, 2026</p>
      
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
        information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mb-4">
        We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection
        and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
      <h3 className="text-xl font-medium mt-6 mb-2">Interpretation</h3>
      <p className="mb-4">
        The words whose initial letters are capitalized have meanings defined under the following conditions. The
        following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-medium mt-6 mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-8 mb-6 space-y-2">
        <li>
          <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
        </li>
        <li>
          <strong>Application</strong> refers to TransitNode ERP, the software program provided by the Company.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to TransitNode ERP.
        </li>
        <li>
          <strong>Country</strong> refers to: Maharashtra, India
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Application.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
      
      <h3 className="text-xl font-medium mt-6 mb-2">Types of Data Collected</h3>
      <h4 className="text-lg font-medium mt-4 mb-2">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul className="list-disc pl-8 mb-6">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
      </ul>

      <h3 className="text-xl font-medium mt-6 mb-2">Use of Your Personal Data</h3>
      <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc pl-8 mb-6 space-y-2">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
        <li><strong>To contact You:</strong> To contact You by email regarding updates or informative communications.</li>
      </ul>

      {/* --- INJECTED PAID CLAUSES (FREE) --- */}
      <div className="bg-blue-50 p-6 rounded-lg my-8 border border-blue-100">
        <h2 className="text-2xl font-semibold mb-4 text-blue-900">Payment Processors (Cashfree)</h2>
        <p className="mb-4">
          We provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
        </p>
        <p className="mb-4">
          We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS.
        </p>
        <p className="mb-4">
          <strong>Cashfree Payments</strong><br />
          Their Privacy Policy can be viewed at <a href="https://www.cashfree.com/privacy/" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">https://www.cashfree.com/privacy/</a>
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-blue-900">GDPR Data Protection Rights</h2>
        <p className="mb-4">We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
        <ul className="list-disc pl-8 mb-6 space-y-1">
          <li><strong>The right to access</strong> – You have the right to request copies of your personal data.</li>
          <li><strong>The right to rectification</strong> – You have the right to request that we correct any information you believe is inaccurate.</li>
          <li><strong>The right to erasure</strong> – You have the right to request that we erase your personal data, under certain conditions.</li>
          <li><strong>The right to restrict processing</strong> – You have the right to request that we restrict the processing of your personal data.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-blue-900">CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
        <p className="mb-4">Under the CCPA, among other rights, California consumers have the right to:</p>
        <ul className="list-disc pl-8 mb-6 space-y-1">
          <li>Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
          <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
          <li>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</li>
        </ul>
      </div>
      {/* --- END INJECTED CLAUSES --- */}

      <h2 className="text-2xl font-semibold mt-8 mb-4">Security of Your Personal Data</h2>
      <p className="mb-4">
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the
        Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to
        protect Your Personal Data, We cannot guarantee its absolute security.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc pl-8 mb-6 space-y-2">
        <li>By email: support@prohitcoretech.com</li>
        <li>
          By visiting this page on our website:{' '}
          <a href="https://www.prohitcoretech.com/contact.html" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">
            https://www.prohitcoretech.com/contact.html
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
